export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DashboardPage } from './DashboardPage'
export { default as BetsPage } from './BetsPage'
export { default as TransactionsPage } from './TransactionsPage'
